const express = require('express');
const app = express();

app.listen(3000, function() {
	console.log('Listening on port 3000');
   });
const fs = require('fs') 
app.engine('hypatia', (filePath, options, callback) => { 
  fs.readFile(filePath, (err, content) => {
    if (err) return callback(err)

    const rendered = content.toString()
      .replace('#title#', '<title>' + options.title + '</title>')
      .replace('#message#', '<h1>' + options.message + '</h1>').replace('#content#','<div>'+ options.content + '</div>' )
    return callback(null, rendered)
  })
})
app.set('views', './views') 
app.set('view engine', 'hypatia')  

app.get('/', (req, res) => {
	res.render('template1', { title: 'FEMALE PAINTERS', message: '12 Famous Female Painters Every Art Lover Should Know', content: '' })
  })
  
app.get('/ANGUISSOLA', (req, res) => {
	res.render('template2', { title: 'SOFONISBA ANGUISSOLA', message: 'SOFONISBA ANGUISSOLA (1532–1625)', content: "Painter Sofonisba Anguissola was a trailblazer during the Italian Renaissance. Born into a relatively poor noble family, her father made sure that she and her sisters had a well-rounded education that incorporated fine art. This included apprenticeships with respected local painters. This set a precedent for future female artists, who until that point typically only apprenticed if a family member had a workshop. Anguissola's talent caught the eye of Michelangelo, with whom she carried on an informal mentorship through the exchange of drawings. Though, as a female artist, she was not allowed to study anatomy or practice drawing models due to its perceived vulgarity, she still managed to have a successful career. Much of her success was owed to her role as a painter in the court of King Philip II of Spain. Over the course of 14 years, she developed her skills for official court portraiture as well as more intimate portraits of nobility. Her paintings are known for capturing the spirit and vibrance of her sitters and can now be found in collections around the world."})
  })
  
app.get('/GENTILESCHI', (req, res) => {
	res.render('template2', { title: 'GENTILESCHI', message: 'ARTEMISIA GENTILESCHI (1593–1653)', content: "As the daughter of an accomplished painter, Artemisia Gentileschi was afforded access to the art world at a young age. Early on she was in her father's workshop mixing paints and he supported her career when he noted that she was exceptionally gifted. As a noted painter of the Italian Baroque period, Artemisia Gentileschi did not let her gender hold her back from her subject matter. She painted large-scale Biblical and mythological paintings, just like her male counterparts and was the first woman accepted to the prestigious Fine Art Academy in Florence.Her legacy is sometimes overshadowed by her biography, with her bloody depictions of Judith and Holofernes often being interpreted through the lens of her rape at the hands of a fellow artist. However, her talent is undeniable and she continues to be recognized for her realistic depiction of the female form, the depth of her colors, and her striking use of light and shadow." })
  })

  app.get('/LEYSTER', (req, res) => {
	res.render('template2', { title: 'LEYSTER', message: 'JUDITH C (1609–1660)', content: "Born in Haarlem, Judith Leyster was a leading artist during the Dutch Golden Age. Typical of Dutch artists during this period, Leyster specialized in genre paintings, still life, and portraits. The details behind her artistic training are unclear, but she was one of the first women admitted to the painter's guild in Haarlem. She later ran a successful workshop with several male apprentices and was known for the relaxed, informal nature of her portraits. While she was quite successful during her lifetime, her reputation suffered after her death due to unfortunate circumstances. Her entire oeuvre was passed off as work either by her contemporary Frans Hals or by her husband. In many cases, her signature was covered by collectors looking to make a profit due to the high market value of Frans Hals' work. Only in the late 19th century were these errors discovered and scholars began to gain a renewed appreciation for Leyster's skill as an artist." })
  })

  app.get('/LE-BRUN', (req, res) => {
	res.render('template2', { title: '/LE-BRUN', message: 'ÉLISABETH VIGÉE LE BRUN (1755–1842)', content: "French portrait artist Élisabeth Vigée Le Brun created an impressive body of work totaling nearly 1,000 portraits and landscape paintings. As the daughter of a painter, she received early instruction from her father and was painting portraits professionally by the time she was a teenager. Her big career break came when she was named as Marie Antoinette's portrait painter and she was later granted entry to numerous art academies. Her paintings bridge the gap between the theatrical Rococo style and more restrained Neoclassical period. She enjoyed continued success in her career, even while in exile after the French Revolution, as she was a favorite painter of the aristocracy across Europe. Sitters enjoyed her ability to put them at ease, which led to portrait paintings that were lively and lacking stiffness. The natural, relaxed manner of her portraits was considered revolutionary at a time when portraiture often called for formal depictions of the upper classes." })
  })

  app.get('/BONHEUR', (req, res) => {
	res.render('template2', { title: 'BONHEUR', message: 'ROSA BONHEUR (1822–1899)', content: "Like many female artists, Rosa Bonheur‘s father was a painter. The French Realist painter is considered one of the most famous female artists of the 19th century, known for her large-format paintings that featured animals. She exhibited regularly at the acclaimed Paris salon and found success abroad in both the United States and Britain. Bonheur spent a great amount of time sketching live animals in motion, accounting for her remarkable ability to capture their likeness on canvas. Bonheur is also celebrated for breaking gender stereotypes. From the mid-1850s onward she wore men's dress, even obtaining police authorization to do so. Though she was often criticized for wearing trousers and loose blouses, she continued to don them throughout her life, citing their practicality when working with animals. She was also an open lesbian, first living with partner Nathalie Micas for over 40 years and then, after Micas' death, forging a relationship with American painter Anna Elizabeth Klumpke. By living her life openly in an era when lesbianism was disparaged by the government, Bonheur staked her claim as a groundbreaking individual both in her career and her personal life." })
  })

  app.get('/MORISOT', (req, res) => {
	res.render('template2', { title: 'MORISOT', message: 'BERTHE MORISOT (1841–1895)', content: "Considered one of the great female Impressionists, Berthe Morisot had art running through her veins. Born into an aristocratic French family, she was the great-niece of celebrated Rococo painter Jean-Honoré Fragonard. Initially, she exhibited her work at the respected Paris Salon before joining the first Impressionist exhibit with Monet, Cézanne, Renoir, and Degas. Morisot has a particularly close relationship with Édouard Manet, who painted several portraits of her, and she eventually married his brother. Her art often focused on domestic scenes and she preferred working with pastels, watercolor, and charcoal. Working mainly in small scale, her light and airy work was often criticized as being too “feminine.” Morisot wrote about her struggles to be taken seriously as a female artist in her journal, stating “I don't think there has ever been a man who treated a woman as an equal and that's all I would have asked for, for I know I'm worth as much as they.”" })
  })

  app.get('/CASSATT', (req, res) => {
	res.render('template2', { title: 'CASSATT', message: 'MARY CASSATT (1844–1926)', content: "American painter Mary Cassatt spent her adult life in France, where she became an integral part of the Impressionist group. Cassatt was born into an affluent family who first protested against her desire to become an artist. She eventually left art school after being frustrated by the separate treatment that the female students received—they couldn't use live models and were left drawing from casts. Upon moving to Paris at age 22, Cassatt sought a private apprenticeship and spent her free time copying Old Master paintings in the Louvre. Cassatt's career was already taking off when she joined the Impressionists and forged a lifelong friendship with Degas. At the same time, she was outspoken in her dismay at the formal art system, which she felt required female artists to flirt or befriend male patrons in order to move ahead. She created her own career path with the Impressionists, mastering pastels to create soft, light work that often highlighted women acting as caretakers. Throughout her life, Cassatt continued to support equality for women, even participating in an exhibition in support of women's suffrage." })
  })

  app.get("/O'KEEFFE", (req, res) => {
	res.render('template2', { title: "O'KEEFFE", message: "GEORGIA O'KEEFFE (1887–1986)", content: "As an artist at the forefront of American Modernism, Georgia O'Keeffe is one of the most celebrated female artists in history. Her early drawings and paintings led to bold experiments in abstraction, with her focus on painting to express her feelings ushering in an era of “Art for Art's Sake.” During her lifetime, her career was intertwined with her husband, Alfred Stieglitz. While the renowned photographer espoused ideas that American art could equal that of Europe and that female painters could create art just as powerful as men, he also hindered interpretation of her work. Stieglitz viewed creativity as an expression of sexuality and these thoughts, coupled with his intimate portraits of O'Keeffe, pushed forward an idea that her close up paintings of flowers were metaphors for female genitalia. It's a concept that the artist has always denied, though her work is undoubtedly sensual. O'Keeffe spent much of her career combatting her art's interpretation solely as a reflection of her gender. Throughout her life she refused to participate in all-female art exhibitions, wishing to be defined simply as an artist, free from gender." })
  })

  app.get('/DE-LEMPICKA', (req, res) => {
	res.render('template2', { title: 'DE LEMPICKA', message: 'TAMARA DE LEMPICKA (1898–1980)', content: "Polish artist Tamara de Lempicka is known for her highly stylized portraits and nudes that exemplify the Art Deco era. De Lempicka spent much of her career in France and the United States, where her work was favored by aristocrats. One of her most famous paintings, Self-Portrait in a Green Bugatti, exemplifies the cool and detached nature of De Lempicka's figures. In the work, which was created for the cover of a German fashion magazine, De Lempicka exudes independence and inaccessible beauty.Her paintings often contained narratives of desire, seduction, and modern sensuality, making them revolutionary for their time. De Lempicka enjoyed success until the outbreak of World War II, but there was a resurgence of interest in her work as Art Deco became popular again in the 1960s. Her immediately recognizable style makes her a particular favorite among fans of Art Deco painters and today her work is more popular than ever, with Madonna being a known collector of her paintings." })
  })

  app.get('/KAHLO', (req, res) => {
	res.render('template2', { title: 'KAHLO', message: 'FRIDA KAHLO (1907–1954)', content: "Currently, there's no other 20th-century female artist with a name as recognizable at Frida Kahlo. While the drama of her tragic accident as a young woman and her tumultuous relationship with husband Diego Rivera have sometimes overshadowed her artistic abilities, there is no denying the power of her painting. She is particularly known for her self-portraits, which deal with themes of identity, suffering, and the human body. Though she was sometimes written about solely as “Diego Rivera's wife” during her lifetime, her artwork has only gained momentum since her death. The most famous Frida Kahlo paintings belong to important art museums around the world, while she has gained status as a champion of feminists, Chicanos, and the LGBT community." })
  })

  app.get('/FRANKENTHALER', (req, res) => {
	res.render('template2', { title: 'FRANKENTHALER', message: 'HELEN FRANKENTHALER (1928–2011)', content: "Growing up in Manhattan, Helen Frankenthaler pursued painting studies at the Dalton School and Bennington College. She began her extensive exhibition career in 1952, with the display of her painting Mountains and Sea. Having studied under the artist Hans Hoffman, as a young artist she became an important figure in the abstract expressionism artistic movement. Her paintings featured colorful, organic shapes. In the early years of her career, these compositions tended to be centralized on the canvas. By the 1960s, Frankenthaler's works often encompassed the entire canvas. Her six-decades-worth of work displays a constant evolution in style. Today, Frankenthaler is remembered as a pioneer of color field painting—a style which features large swaths of color as the painting's “subject.” To achieve the effect of a wash of brilliant color, Frankenthaler thinned her paints with turpentine before applying them to the unprimed canvas. The result of this “soak stain” method was an almost-watercolor-like appearance with color built in organic layers. Hers and similar works were included in the famous 1964 exhibit curated by art critic Clement Greenberg, entitled Post-Painterly Abstraction. Today, her work can be found in most major American art museums." })
  })

  app.get('/LEAF', (req, res) => {
	res.render('template2', { title: 'LEAF', message: 'JUNE LEAF (1929–PRESENT)', content: "Born and raised in Chicago, June Leaf briefly trained at the IIT Institute of Design before setting out to pursue her own independent learning in Paris at the tender age of 18. In 1954, she returned to Illinois to obtain her bachelor's and master's degrees in Art Education. However, in 1958 she returned to Paris with funding for her artwork from a Fulbright. Over the years, she developed an allegorical style across several mediums. Through pen and ink drawings, canvas paintings, and kinetic sculpture, Leaf's work embraces the abstract and unusual. Her work often features the human body—often incorporating her own imagined hands into the work. Leaf and her husband—filmmaker and photographer Robert Frank—split their time between a Bleeker Street apartment in New York and fishing cottage in Nova Scotia. In 2016, the Whitney Museum of American Art held a retrospective on her work entitled June Leaf: Thought Is Infinite. Although Frank passed away in 2019, Leaf still creates. In a 2016 interview with Women's Wear Daily, she described her work as a process of searching. She said, “Maybe I don’t want public acclaim. I want to survive with that integrity that is so precious to me. The fact that I could make that drawing [gesturing toward an easel] made me think ‘Oh good, you’re still a scientist who can invent something that goes with your life.'”" })
  })